language: python
python:
  - "3.8"

stages:
  - validation
  - test

install:
  - pip install pipenv
  - pipenv install --dev

jobs:
  include:
    - stage: validation
      script: black .
      script: flake8 .

    - stage: test  
      script:
        - python -m pytest --cov=myproject test/unit_test/

  