language: python
python:
  - "3.8"

virtualenv:
  system_site_packages: true

install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - python -m pytest --cov=myproject test/unit_test/
  